Console Window UI
wikitools/wikigraph pull request #23
Opened 2019-11-05 13:10 UTC by mikolajmirko

Console Window UI element mock-up prepared. Empty controller file created.

2019-11-05 13:50 UTC, stasgora requested changes

2019-11-05 13:50 UTC, stasgora commented on Assets/WIKIGRAPH.unity
> +GameObject:
Without an ```Event System``` I am not able to interact with the console in any way

2019-11-05 13:50 UTC, stasgora commented on Assets/Scripts/Controllers/ConsoleWindowController.cs
> +			isServer = networkController.IsServer();
We can already do showing & hiding the console if we are on server and a certain button is pressed (using PCButton in both PC & Cave binding since it will be performed using keyboard)

2019-11-05 13:55 UTC, mikolajmirko commented on Assets/Scripts/Controllers/ConsoleWindowController.cs
> +			isServer = networkController.IsServer();
I have written showing/hinding the element depending on isServer variable, but I don't know how to test it, that is why the controller is empty and this has only front-end changes.

2019-11-06 19:59 UTC, stasgora requested changes

2019-11-06 19:59 UTC, stasgora commented on Assets/Scripts/Controllers/ConsoleWindowController.cs
> +			Image headerIcon = transform.Find("ConsoleHeader/NodeIcon").GetComponent<Image>();
Can we do that in Awake/Start?

2019-11-06 19:59 UTC, stasgora commented on Assets/Scripts/Controllers/InputController.cs
> +			ConsoleController = GameObject.Find("/Console Window").GetComponent<ConsoleWindowController>();
FindObjectsOfTypeAll

2019-11-06 19:59 UTC, stasgora commented on Assets/WIKIGRAPH.unity
> +GameObject:
Scaling not present

2019-11-06 21:34 UTC, stasgora approved these changes

2019-11-06 21:35 UTC, merged